baseURL = "https://hisashitoku.github.com/"
title = "Hisashi Toku's Homepage "
copyright = "Copyright Â© 2018, HisashiToku"
languageCode = "ja-jp" #en-US
theme = "indigo"
paginate = 3

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  Author = "Hisashi Toku"
  Description = "Description of website for head meta tag"
  Subtitle = "åºœå¤§åšå£«ç ”ç©¶å®¤"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = true
  PermalinkText = "ğŸ”—"

  # Contact/social-network identifiers for social icons
  EmailAddress = "tokuhisashi@example.com"


  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "tokuhisahsi@example.com"
    Country = "Japan"
    City = "Osaka"
